DROP INDEX IF EXISTS idx_mnemosyne_embedding;
DROP INDEX IF EXISTS idx_mnemosyne_filter;
DROP INDEX IF EXISTS idx_mnemosyne_entity;
DROP TABLE IF EXISTS mnemosyne_memories;

-- Reverse the RLS hardening from 002 up.
ALTER TABLE orgs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE questions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE candidates NO FORCE ROW LEVEL SECURITY;
ALTER TABLE applications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE interviews NO FORCE ROW LEVEL SECURITY;
ALTER TABLE interview_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE company_contexts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_prompts NO FORCE ROW LEVEL SECURITY;

ALTER FUNCTION login_lookup(TEXT, TEXT) OWNER TO CURRENT_USER;
ALTER FUNCTION validate_interview_token(TEXT) OWNER TO CURRENT_USER;

REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM intivai_app;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM intivai_app;
REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM intivai_rls_bypass;
ALTER DEFAULT PRIVILEGES FOR ROLE intivai IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM intivai_app;
ALTER DEFAULT PRIVILEGES FOR ROLE intivai IN SCHEMA public
    REVOKE USAGE, SELECT ON SEQUENCES FROM intivai_app;
ALTER DEFAULT PRIVILEGES FOR ROLE intivai IN SCHEMA public
    REVOKE SELECT ON TABLES FROM intivai_rls_bypass;
REVOKE USAGE ON SCHEMA public FROM intivai_app;
DO $$ BEGIN
    EXECUTE format('REVOKE CONNECT ON DATABASE %I FROM intivai_app', current_database());
END $$;
DROP ROLE IF EXISTS intivai_rls_bypass;
DROP ROLE IF EXISTS intivai_app;
