ALTER TABLE candidates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE company_contexts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
